name: Lint

on: push

jobs:
  run-linters:
    name: Run Linter checks
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm

      - name: Install Node.js dependencies
        run: pnpm install --frozen-lockfile

      - name: Run ESLint and Prettier
        uses: wearerequired/lint-action@v2.3.0
        env:
          CI: true
        with:
          eslint: true
          eslint_extensions: "ts,tsx"
          prettier: true
          prettier_extensions: "js,ts,tsx,scss"
