name: Storybook

on: [push]

jobs:
  e2e:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v4

    - name: Cache node modules
      uses: actions/cache@v4
      env:
        cache-name: cache-node-modules
      with:
        path: "**/node_modules"
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - run: npm install

    - run: npm run build-storybook
      env:
        NODE_ENV: production

    - run: npm run loki:static-build
      env:
        CI: true

    - uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: loki
        path: |
          .loki
          !.loki/reference

