name: Test

on: [ push ]

jobs:
  unit:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 18.x ]
        react-version: [ 18 ]

    steps:
    - uses: actions/checkout@v2

    - name: Cache node modules
      uses: actions/cache@v3
      env:
        cache-name: cache-node-modules
      with:
        path: "**/node_modules"
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.react-version }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.react-version }}-
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - run: npm install

    - name: Install React ${{ matrix.react-version }}
      env:
        REACT_VERSION: ${{ matrix.react-version }}
      run: |
        npm run react:uninstall \
          && npm run react:install-version

    - run: npm run build

    - run: npm run test
      env:
        CI: true
